email_template
GreenRoads-FL/bigcommerce-api-ruby pull request #1
Opened 2022-03-21 23:35 UTC by william1benn

Endpoint to retrieve email templates from BC store.

2022-03-22 09:49 UTC, gorodnov requested changes

2022-03-22 09:49 UTC, gorodnov commented on lib/bigcommerce/resources/v3/email_template.rb
> +      property :translations
@william1benn I think you can add `coerce: Array` param to this property, so it will be automatically handled as an array

2022-03-22 09:49 UTC, gorodnov commented on lib/bigcommerce/resources/v3/email_template.rb
> +      property :meta
I think `:meta` property won't work, it is meta information about the response but not a part of `EmailTemplate` object.

2022-03-28 14:40 UTC, william1benn commented on lib/bigcommerce/resources/v3/email_template.rb
> +      property :meta
I see it is part of the response, but about the response.

2022-03-28 18:49 UTC, gorodnov approved these changes

2022-03-31 13:55 UTC, merged